import {
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_TITLE,
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'Inicio',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'admin',
        path: '',
        title: 'Administración',
        translateKey: 'nav.admin.root',
        icon: 'admin',
        type: 'collapse',
        authority: ['admin', 'User'],
        subMenu: [
            {
                key: 'admin.personal',
                path: '/admin/personal',
                title: 'Personal',
                translateKey: 'nav.admin.personal',
                icon: '',
                type: 'item',
                authority: ['admin', 'User'],
                subMenu: [],
            },
            {
                key: 'admin.sucursales',
                path: '/admin/sucursales',
                title: 'Sucursales',
                translateKey: 'nav.admin.sucursales',
                icon: '',
                type: 'item',
                authority: ['admin', 'User'],
                subMenu: [],
            },
            {
                key: 'admin.proveedores',
                path: '/admin/proveedores',
                title: 'Proveedores',
                translateKey: 'nav.admin.proveedores',
                icon: '',
                type: 'item',
                authority: ['admin', 'User'],
                subMenu: [],
            },
            {
                key: 'admin.cheques',
                path: '/admin/cheques',
                title: 'Cheques',
                translateKey: 'nav.admin.cheques',
                icon: '',
                type: 'item',
                authority: ['admin', 'User'],
                subMenu: [],
            },
            {
                key: 'admin.doctores',
                path: '/admin/doctores',
                title: 'Doctores',
                translateKey: 'nav.admin.doctores',
                icon: '',
                type: 'item',
                authority: ['admin', 'User'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'clients',
        path: '',
        title: 'Clientela',
        translateKey: 'nav.clients',
        icon: 'clients',
        type: 'collapse',
        authority: ['admin', 'User'],
        subMenu: [
            {
                key: 'clients.clientes',
                path: '/clientes/clientes',
                title: 'Clientes',
                translateKey: 'nav.clients.clientes',
                icon: '',
                type: 'item',
                authority: ['admin', 'User'],
                subMenu: [],
            },
            {
                key: 'clients.empresas',
                path: '/clientes/empresas',
                title: 'Empresas',
                translateKey: 'nav.clients.empresas',
                icon: '',
                type: 'item',
                authority: ['admin', 'User'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'products',
        path: '',
        title: 'Productos',
        translateKey: 'nav.products',
        icon: 'products',
        type: 'collapse',
        authority: ['admin', 'User'],
        subMenu: [
            {
                key: 'uiComponent.common.button',
                path: '/button',
                title: 'Productos',
                translateKey: 'nav.uiComponentsCommon.button',
                icon: '',
                type: 'item',
                authority: ['admin', 'User'],
                subMenu: [],
            },
            {
                key: 'uiComponent.common.typography',
                path: '/typography',
                title: 'Cristales',
                translateKey: 'nav.uiComponentsCommon.typography',
                icon: '',
                type: 'item',
                authority: ['admin', 'User'],
                subMenu: [],
            },
            {
                key: 'uiComponent.common.typography',
                path: '/typography',
                title: 'Marcas',
                translateKey: 'nav.uiComponentsCommon.typography',
                icon: '',
                type: 'item',
                authority: ['admin', 'User'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'sales',
        path: '',
        title: 'Ventas',
        translateKey: 'nav.sales',
        icon: 'sales',
        type: 'collapse',
        authority: ['admin', 'User'],
        subMenu: [
            {
                key: 'uiComponent.common.button',
                path: '/button',
                title: 'Ventas',
                translateKey: 'nav.uiComponentsCommon.button',
                icon: '',
                type: 'item',
                authority: ['admin', 'User'],
                subMenu: [],
            },
            {
                key: 'uiComponent.common.typography',
                path: '/typography',
                title: 'Pagos',
                translateKey: 'nav.uiComponentsCommon.typography',
                icon: '',
                type: 'item',
                authority: ['admin', 'User'],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
